### PR TITLE
Update to v1.1.1

### PR DESCRIPTION
**Pull request by farribeiro**
Update the program and deps.

### CODE REVIEW

**Comment by farribeiro** [comment]
New dependency ... 

Magick++ (from imagemagick)

Needs check whats args sent to new dep

**Comment by farribeiro** [comment]
bot, build eu.scarpetta.PDFMixTool

**Comment by yodatak** [comment]
any news on this ?

**Comment by rsrchboy** [comment]
...bump?

**Comment by farribeiro** [comment]
bot, build eu.scarpetta.PDFMixTool

**Comment by farribeiro** [comment]
@marcoscarpetta LGTM

**Pull request merged**
